replicaCount: 3
image:
  repository: gitlab.com/winis/winis-io/master
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://api.winisapp.com
  externalPort: 80
  internalPort: 3000
mongodb:
  enabled: true
  replicaSet:
    enabled: true
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 128Mi
