stages:
  - test
  - build
  - review
  - production
  - cleanup

test:
  stage: test
  image: node:8
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - node_modules/
  coverage: '/^All files\s*\|\s*(\d{1,3}(?:\.\d+)?)/'
  variables:
    NODE_ENV: test
  script:
    - npm install
    - npm run test-coverage
  only:
    - branches

lint:
  stage: test
  image: node:8
  cache:
    key: "$CI_COMMIT_REF_SLUG-lint"
    paths:
      - node_modules/
  script:
    - npm install
    - npm run lint
  only:
    - branches

build:assets:
  stage: build
  image: node:8
  script:
    - npm install -g npm bower
    - bower install --allow-root -config.interactive=false
  artifacts:
    paths:
      - client/

review:
  stage: review
  image: google/cloud-sdk:latest
  dependencies:
    - build:assets
  script:
    - init_gcloud
    - gcloud app deploy --version $CI_COMMIT_REF_NAME --no-promote
    - persist_environment_url
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_NAME-dot-winis-be.appspot.com
    on_stop: stop_review
  artifacts:
    paths: [environment_url.txt]
  only:
    refs:
      - branches
    kubernetes: active
  except:
    - master

stop_review:
  stage: cleanup
  image: google/cloud-sdk:latest
  variables:
    GIT_STRATEGY: none
  script:
    - init_gcloud
    - gcloud app versions delete $CI_COMMIT_REF_NAME
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  only:
    refs:
      - branches
    kubernetes: active
  except:
    - master

production:
  stage: production
  image: google/cloud-sdk:latest
  dependencies:
    - build:assets
  variables:
    GIT_STRATEGY: fetch
  script:
    - init_gcloud
    - gcloud app deploy
    - persist_environment_url
  environment:
    name: production
    url: https://winis-be.appspot.com
  artifacts:
    paths: [environment_url.txt]
  only:
    refs:
      - master
    kubernetes: active

# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x

  function init_gcloud() {
    echo $GOOGLE_APP_ENGINE_KEY > /tmp/$CI_PIPELINE_ID.json
    gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    gcloud config set project winis-be
    gcloud info
  }

  function persist_environment_url() {
    echo "https://$CI_COMMIT_REF_NAME-dot-winis-be.appspot.com" > environment_url.txt
  }

before_script:
  - *auto_devops
