runtime: nodejs8

instance_class: F2

handlers:
- url: /js
  static_dir: client/public/js

- url: /css
  static_dir: client/public/css

- url: /bower_components
  static_dir: client/bower_components

- url: /img
  static_dir: client/public/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
