version: '2.1'
services:
  app:
    build: .
    container_name: "winis-io"
    environment:
      - NODE_ENV=docker
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/zenbrain --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    command: mongod --smallfiles --logpath=/dev/null
